resolves a missing dependency error
documented here; https://stackoverflow.com/questions/67882261/modulenotfounderror-no-module-named-werkzeug-posixemulation

tests.test_parameters (nose2.loader.ModuleImportFailure) ... ERROR
tests.test_logic (nose2.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: tests.test_parameters (nose2.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_parameters
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nose2/plugins/loader/discovery.py", line 201, in _find_tests_in_file
    module = util.module_from_name(module_name)
  File "/usr/local/lib/python3.6/site-packages/nose2/util.py", line 77, in module_from_name
    __import__(name)
  File "/app/tests/test_parameters.py", line 3, in <module>
    from gutenberg_http import parameters
  File "/app/gutenberg_http/__init__.py", line 17, in <module>
    cache = Cache(app, config={'CACHE_TYPE': 'simple'})
  File "/usr/local/lib/python3.6/site-packages/flask_caching/__init__.py", line 166, in __init__
    self.init_app(app, config)
  File "/usr/local/lib/python3.6/site-packages/flask_caching/__init__.py", line 212, in init_app
    self._set_cache(app, config)
  File "/usr/local/lib/python3.6/site-packages/flask_caching/__init__.py", line 217, in _set_cache
    from . import backends
  File "/usr/local/lib/python3.6/site-packages/flask_caching/backends/__init__.py", line 12, in <module>
    from flask_caching.backends.filesystem import FileSystemCache
  File "/usr/local/lib/python3.6/site-packages/flask_caching/backends/filesystem.py", line 7, in <module>
    from werkzeug.posixemulation import rename
ModuleNotFoundError: No module named 'werkzeug.posixemulation'